DROP TABLE SQUADRA;

--SQUADRA 
CREATE TABLE SQUADRA(
CATEGORIA_S VARCHAR2(15),
ETA_S NUMBER(2,0),
N_PATENTINO_SQUADRA CHAR(7) ,
CONSTRAINT SQUADRA_PK PRIMARY KEY(CATEGORIA_S,ETA_S),
CONSTRAINT SQUADRA_FK FOREIGN KEY(N_PATENTINO_SQUADRA) REFERENCES MISTER(N_PATENTINO),
CONSTRAINT CONTROLLO_ETA CHECK((ETA_S>=5 AND ETA_S<7 AND UPPER(CATEGORIA_S)IN 'PICCOLI AMICI') OR 
							  (ETA_S>=7 AND ETA_S<9 AND UPPER(CATEGORIA_S) IN('PULCINI'))      OR 
							  (ETA_S>=9 AND ETA_S<12 AND UPPER(CATEGORIA_S)IN 'ESORDIENTI')    OR 
							  (ETA_S>=12 AND ETA_S<=14 AND UPPER(CATEGORIA_S)IN 'GIOVANISSIMI'))
);